language: go
go:
  - 1.9
  - 1.11
  - 1.12
  - tip
install:
  - go get github.com/bmizerany/assert
  - go get github.com/philhofer/fwd
  - go get github.com/tinylib/msgp
sudo: false
matrix:
  allow_failures:
    - go: tip
